# Model configuration
model:
  pretrained_model_name: "stabilityai/stable-diffusion-xl-base-1.0"
  model_type: "sdxl"
  prediction_type: "epsilon"
  num_timesteps: 1000
  sigma_min: 0.002
  sigma_max: 2000.0
  timestep_bias_strategy: "none"
  timestep_bias_min: 0.0
  timestep_bias_max: 1.0

# Optimizer settings
optimizer:
  learning_rate: 1.0e-6
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8
  optimizer_type: "adamw_bf16"  # Options: adamw, adamw_bf16, adamw_8bit, lion, prodigy

# Training configuration
training:
  batch_size: 4
  num_epochs: 100
  save_every: 1
  method: "ddpm"  # Options: ddpm, flow_matching
  num_workers: 4
  pin_memory: true
  gradient_accumulation_steps: 1
  mixed_precision: "bf16"  # Options: fp16, bf16, no
  enable_xformers: true
  clip_grad_norm: 1.0
  num_inference_steps: 50

# Dataset configuration
data:
  train_data_dir: 
    - "D:\\Datasets\\High-quality-photo10k"  # Can be single path or list of paths
  validation_data_dir: null  # Optional validation data directory
  image_size: 1024
  center_crop: true
  random_flip: true
  tokenizer_max_length: 77

# Global configuration settings
global_config:
  # Cache settings
  cache:
    cache_dir: "cache"
    max_cache_size: 10000
    enable_cache: true
    cache_latents: true
    cache_text_embeddings: true

  # Logging configuration
  logging:
    use_wandb: false
    wandb_project: "sdxl-training"
    wandb_entity: null  # Your wandb username or team name
    log_dir: "logs"
    filename: "training.log"
    console_level: "INFO"
    file_level: "DEBUG"
    capture_warnings: true
    log_every: 10

  # Image processing settings (referenced in pipeline.py)
  image:
    supported_dims:
      - [1024, 1024]   # Square
      - [1024, 1536]   # Portrait
      - [1536, 1024]   # Landscape
      - [1024, 1536]   # Portrait
      - [1536, 1024]   # Landscape
      - [1024, 1536]   # Portrait
      - [1536, 1024]   # Landscape
    max_aspect_ratio: 2.0  # Maximum allowed aspect ratio deviation
