# Model configuration
model:
  pretrained_model_name: "stabilityai/stable-diffusion-xl-base-1.0"
  model_type: "sdxl"
  prediction_type: "v_prediction"
  num_timesteps: 1000
  sigma_min: 0.002
  sigma_max: 20000.0
  use_ztsnr: true
  timestep_bias_strategy: "none"
  timestep_bias_min: 0.0
  timestep_bias_max: 1.0
  min_snr_gamma: 5.0

# Optimizer settings
optimizer:
  learning_rate: 4.0e-7
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8
  optimizer_type: "adamw_bf16"  # Options: adamw, adamw_bf16, adamw_schedule_free_kahan, SOAP

# Training configuration
training:
  batch_size: 4
  num_epochs: 10
  save_every: 1
  method: "ddpm"  # Options: ddpm, flow_matching
  prediction_type: "v_prediction"
  num_workers: 4
  pin_memory: true
  gradient_accumulation_steps: 4  # Fixed to 4 steps for stable training
  mixed_precision: "bf16"  # Options: fp16, bf16, no
  enable_xformers: true
  clip_grad_norm: 1.0
  num_inference_steps: 50
  debug_mode: false
  save_final_model: true
  method_config:
    scheduler:
      rescale_betas_zero_snr: true
      dynamic_thresholding_ratio: 0.995
      sample_max_value: 20000.0
      timestep_spacing: "leading"

# Dataset configuration
data:
  train_data_dir: 
    - "D:\\work\\trainngsdxl\\High-quality-photo10k"  # Can be single path or list of paths
  validation_data_dir: null  # Optional validation data directory
  image_size: 1024
  center_crop: true
  random_flip: true
  tokenizer_max_length: 77

# Global configuration settings
global_config:
  # Cache settings
  cache:
    cache_dir: "cache"
    max_cache_size: 10000
    use_cache: false
    cache_latents: false
    cache_text_embeddings: false

  # Logging configuration
  logging:
    use_wandb: true
    wandb_project: "sdxl-training"
    wandb_entity: "izquierdoxander"  # Your wandb username or team name
    log_dir: "logs"
    filename: "training.log"
    console_level: "INFO"
    file_level: "INFO"
    capture_warnings: true
    log_every: 10

  # Image processing settings
  image:
    supported_dims:
      # Primary SDXL aspect ratios (all within 589k-1.04M pixels)
      - [640, 1536]   # 983k pixels
      - [768, 1344]   # 1032k pixels
      - [832, 1216]   # 1012k pixels
      - [896, 1152]   # 1032k pixels
      - [1024, 1024]  # 1048k pixels (square)
      - [1152, 896]   # 1032k pixels
      - [1216, 832]   # 1012k pixels
      - [1344, 768]   # 1032k pixels
      - [1536, 640]   # 983k pixels
    max_aspect_ratio: 2.4      # Matches 1536/640
    target_size: [1024, 1024]  # SDXL optimal square
    max_size: [1536, 1536]     # SDXL max dimension
    min_size: [384, 384]       # SDXL minimum useful size
    bucket_step: 64            # Required for SDXL to avoid 6N IndexError

# Tag weighting configuration
tag_weighting:
  enable_tag_weighting: false    # Set to true to enable tag weighting
  use_cache: false
  min_weight: 0.1
  max_weight: 3.0
  default_weight: 1.0
  smoothing_factor: 0.05       # Add smoothing factor configuration

