global_config:
  image:
    target_size: [1024, 1024]
    supported_dims:
    # Original dimensions
    - [1024, 1024]  # 1:1
    - [1152, 896]   # ~1.29:1
    - [896, 1152]   # 1:1.29
    - [1216, 832]   # ~1.46:1
    - [832, 1216]   # 1:1.46
    - [1344, 768]   # 1.75:1
    - [768, 1344]   # 1:1.75
    - [1536, 640]   # 2.4:1
    - [640, 1536]   # 1:2.4

    # Medium dimensions
    - [1280, 832]   # ~1.54:1
    - [832, 1280]   # 1:1.54
    - [1408, 704]   # 2:1
    - [704, 1408]   # 1:2
    - [1472, 672]   # ~2.19:1
    - [672, 1472]   # 1:2.19
    - [1600, 608]   # ~2.63:1
    - [608, 1600]   # 1:2.63
    - [1088, 960]   # ~1.13:1
    - [960, 1088]   # 1:1.13
    - [1024, 896]   # ~1.14:1
    - [896, 1024]   # 1:1.14
    - [1280, 768]   # ~1.67:1
    - [768, 1280]   # 1:1.67

    # Large dimensions (2048-based)
    - [2048, 2048]  # 1:1
    - [2048, 1920]  # ~1.07:1
    - [1920, 2048]  # 1:1.07
    - [2048, 1792]  # ~1.14:1
    - [1792, 2048]  # 1:1.14
    - [2048, 1664]  # ~1.23:1
    - [1664, 2048]  # 1:1.23
    - [2048, 1536]  # 1.33:1
    - [1536, 2048]  # 1:1.33
    - [2048, 1408]  # ~1.45:1
    - [1408, 2048]  # 1:1.45
    - [2048, 1280]  # 1.6:1
    - [1280, 2048]  # 1:1.6
    - [2048, 1152]  # ~1.78:1
    - [1152, 2048]  # 1:1.78
    - [2048, 1024]  # 2:1
    - [1024, 2048]  # 1:2
    - [2048, 896]   # ~2.28:1
    - [896, 2048]   # 1:2.28
    - [2048, 768]   # ~2.67:1
    - [768, 2048]   # 1:2.67
    - [2048, 704]   # ~2.91:1
    - [704, 2048]   # 1:2.91
    max_size: [2048, 2048]
    min_size: [256, 256]
    max_dim: 4194304  # 2048 * 2048
    max_aspect_ratio: 3.0  # Maximum allowed aspect ratio for images
  cache:
    cache_dir: "cache"
    use_cache: true
    clear_cache_on_start: false
  seed: null
  output_dir: "outputs"
  logging:
    console_level: "DEBUG"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
    file_level: "DEBUG"
    log_dir: "outputs/wslref/logs"
    filename: "train.log"

model:
  pretrained_model_name: "stabilityai/stable-diffusion-xl-base-1.0"
  enable_memory_efficient_attention: true
  enable_vae_slicing: false
  enable_model_cpu_offload: false
  enable_sequential_cpu_offload: false
  enable_bf16_training: true
  dtype: "bfloat16"
  fallback_dtype: "float32"
  prediction_type: "v_prediction"

training:
  batch_size: 4
  micro_batch_size: 4  # Add this line
  gradient_accumulation_steps: 1
  mixed_precision: true
  gradient_checkpointing: true
  method: "ddpm"  # Valid values: "ddpm" or "flow_matching"
  num_timesteps: 1000
  snr_gamma: 5.0
  zero_terminal_snr: true
  sigma_min: 0.002
  sigma_max: 2000.0
  rho: 7.0
  scheduler:
    num_train_timesteps: 1000
    beta_start: 0.00085
    beta_end: 0.012
    beta_schedule: "scaled_linear"
    timestep_spacing: "uniform" #options are "leading", "trailing", "uniform"
    rescale_betas_zero_snr: true
  # Flow matching specific settings (used only when method is "flow_matching")
  sigma: 1.0
  time_sampling: "uniform"

data:
  # Supports both Windows and Unix paths
  # Windows paths (D:\Dataset) will be automatically converted to WSL paths (/mnt/d/Dataset)
  train_data_dir: 
    - "D:\\Datasets\\High-quality-photo10k"  # Windows path
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  proportion_empty_prompts: 0.05

tag_weighting:
  enable_tag_weighting: true
  use_cache: true
  default_weight: 1.0
  min_weight: 0.1
  max_weight: 3.0
  smoothing_factor: 0.1

